language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - SHA=${TRAVIS_COMMIT}

script:
  - mvn package

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login-password --region "eu-west-1")
  - docker build -t 832237568284.dkr.ecr.eu-west-1.amazonaws.com/devicenator-api:${SHA} .
  - docker push 832237568284.dkr.ecr.eu-west-1.amazonaws.com/devicenator-api:${SHA}

notifications:
  email: false
