language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - SHA=${TRAVIS_COMMIT}

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - mvn package || travis_terminate 1
  - ./infrastructure/build-docker-image.sh || travis_terminate 1

notifications:
  email: false
