language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn package

after_success:
  - docker build -t aidamanna/devicenator:${TRAVIS_BUILD_NUMBER} .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin aidamanna.com
  - docker push aidamanna/devicenator:${TRAVIS_BUILD_NUMBER}

notifications:
  email: false
