language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn package

after_success:
  - docker build -t aidamanna/devicenator:${TRAVIS_BUILD_NUMBER} .
  - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
  - docker push aidamanna/devicenator:${TRAVIS_BUILD_NUMBER}

notifications:
  email: false
