language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - SHA=${TRAVIS_COMMIT}

script:
  - mvn package

after_success:
  - docker build -t aidamanna/devicenator:${SHA} .
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
  - docker push aidamanna/devicenator:${SHA}

notifications:
  email: false
