version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
    - './var/elasticsearch:/usr/share/elasticsearch/data'

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    ports: ['9600:9600']
    depends_on: ['elasticsearch']
    volumes:
    - './etc/logstash/pipeline:/usr/share/logstash/pipeline'
    - './var/logs:/logs'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports: ['5601:5601']
    depends_on:
    - 'elasticsearch'

  devicenator:
    build: .
    container_name: devicenator
    ports: ['8080:8080']