apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: devicenator
  name: devicenator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: devicenator
  type: NodePort
status:
  loadBalancer: {}
