apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicenator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: devicenator
  template:
    metadata:
      labels:
        component: devicenator
    spec:
      containers:
        - name: devicenator
          image: aidamanna/devicenator
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
