spring:
  h2:
    console:
      enabled: true
  security:
    user:
      name: aida
      password: none

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-service:5432/devicenator

  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-service:5432/devicenator
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

info:
  app:
    name: devicenator
    description: "Book devices in your device-lab"

---
spring:
  profiles: dev

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true