spring:
  h2:
    console:
      enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-service:5432/devicenator

  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-service:5432/devicenator
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

info:
  app:
    name: devicenator
    description: "Book devices in your device-lab"

server:
  ssl:
    key-store: keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443

---
spring:
  profiles: dev

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true