spring:
  h2:
    console:
      enabled: true

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

info:
  app:
    name: devicenator
    description: "Book devices in your device-lab"
